export const story = {
  site: {
    title: "365",
    description: "A story of one unforgettable year.",
  },
  ui: {
    chapterNextArrow: "↓",
  },
  landing: {
    preloaderTitle: "365",
    loadingLabel: "Loading memories...",
    title: "365",
    lines: [
      { id: "year-ago", text: "Exactly one year ago, you were just another person I'd yet to know." },
      { id: "today", text: "Today... you're one of the people I trust the most." },
      { id: "chapter", text: "Funny how an ordinary year quietly became one of the most beautiful chapters of my life." },
    ],
    button: "Begin the story",
    buttonArrow: "→",
    dateRange: "July 2025 — July 2026",
  },
  beforeUs: {
    chapter: "Chapter I",
    title: "Before Us",
    lines: [
      { id: "strangers", text: "Every meaningful story begins with two strangers." },
      { id: "quietly", text: "Ours began so quietly that neither of us could have guessed what it would become." },
      { id: "safe-place", text: "We didn't know we were meeting someone who would eventually become one of the safest places in each other's lives." },
    ],
    scrollHint: "Keep Scrolling",
    next: { label: "Continue to Conversations", target: "chapter-2" },
  },
  conversations: {
    chapter: "Chapter II",
    title: "Conversations",
    messages: [
      { id: "ordinary", side: "left", text: "It all started with ordinary conversations." },
      { id: "daily", side: "right", text: "Then somehow... those conversations became part of my day." },
      { id: "silence", side: "left", text: "The kind where silence was never awkward." },
      { id: "memories", side: "right", text: "The kind where even random moments became memories." },
    ],
    closing: "Somewhere between the jokes, the random conversations, and the endless messages... I found a friend I never expected to mean this much.",
    next: { label: "Continue to Trust", target: "chapter-3" },
  },
  trust: {
    chapter: "Chapter III",
    title: "Trust",
    pillars: [
      { id: "trust", title: "Trust", text: "Somehow, being honest with you always felt effortless." },
      { id: "comfort", title: "Comfort", text: "Even ordinary conversations could turn an exhausting day into a lighter one." },
      { id: "support", title: "Support", text: "You reminded me that showing up for someone is often louder than words." },
      { id: "home", title: "Home", text: "Some people become familiar places. You became one of mine." },
    ],
    closing: "I don't know exactly when it happened, but somewhere along the way, you stopped being just someone I knew... and quietly became someone I genuinely trust.",
    next: { label: "Continue to Compass", target: "chapter-5" },
  },
  compass: {
    chapter: "Chapter V",
    title: "Compass",
    lines: [
      { id: "direction", text: "Life has a funny way of making us question our own direction." },
      { id: "answers", text: "There were days when I wasn't searching for answers. I was simply trying to make sense of everything around me." },
      { id: "path", text: "You never told me what path to take." },
    ],
    sequence: [
      { id: "you", text: "You", emphasized: false },
      { id: "listened", text: "listened.", emphasized: false },
      { id: "questioned", text: "Questioned.", emphasized: false },
      { id: "encouraged", text: "Encouraged.", emphasized: false },
      { id: "stayed", text: "Stayed.", emphasized: true },
    ],
    ending: [
      { id: "direction-again", text: "Somewhere along the way, without even realizing it, I started finding my own direction again." },
      { id: "north", text: "A compass never decides where you should go. It simply reminds you where north is." },
      { id: "thanks", text: "Thank you for never trying to write my story... only for helping me become a better author of it." },
    ],
    scrollHint: "Keep Going",
    next: { label: "Continue Beyond Miles", target: "chapter-6" },
  },
  beyondMiles: {
    chapter: "Chapter VI",
    title: "Beyond Miles",
    opening: ["We never really needed the same place...", "to feel like we were never far apart."],
    route: "📍──────────────📍",
    routeLabel: "Different Cities",
    lines: [
      "Some of our best conversations happened through a screen.",
      "Somehow, a call could make an ordinary day lighter...",
      "...and a difficult one feel a little less heavy.",
    ],
    distanceTitle: "Distance",
    distanceSubtitle: "was never measured in kilometers.",
    closing: "It was measured by how often we chose to be there for each other.",
    next: { label: "Continue to Moments", target: "chapter-7" },
  },
  moments: {
    chapter: "Chapter VII",
    title: "Moments",
    items: [
      { id: "calls", emoji: "📞", title: "The Calls", text: "There were so many days when everything felt a little overwhelming. And somehow, almost magically, your call would come. Sometimes you wanted to hear me, sometimes you just wanted to share your own day. You probably never realized it, but every conversation reminded me that my existence mattered to someone." },
      { id: "laughter", emoji: "😂", title: "The Laughter", text: "You making the weirdest expressions and me acting like the dumbest person alive somehow became our favorite comedy show. We laughed at each other far more than we laughed at jokes, and I honestly wouldn't trade those moments for anything." },
      { id: "pride", emoji: "🌱", title: "The Pride", text: "Watching you choose singing, creating content, following your niyamas, and becoming more like yourself has been one of my favorite things to witness. I don't just admire your achievements—I admire the person you're becoming." },
      { id: "fights", emoji: "🤍", title: "The Fights", text: "We weren't perfect. We argued. Sometimes I hurt your incredibly pure heart, and I still wish I could take those moments back. But what makes me grateful is that every single time, we chose understanding over ego and our friendship over winning." },
    ],
    closingTitle: "Maybe these were just moments.",
    closingLines: ["But together...", "they became fifteen beautiful months."],
    next: { label: "Continue to the Letter", target: "chapter-8" },
  },
  letter: {
    next: { label: "Continue Through My Eyes", target: "chapter-9" },
    lines: [
      { id: "greeting", text: "Dear You," }, { id: "space-1", text: "" },
      { id: "changed", text: "I don't think you realize how much these fifteen months have changed me." }, { id: "space-2", text: "" },
      { id: "quietly", text: "You walked into my life so quietly..." }, { id: "smile", text: "yet somehow became one of the loudest reasons I smile." }, { id: "space-3", text: "" },
      { id: "calls", text: "Thank you for every random call." }, { id: "jokes", text: "Thank you for every stupid joke." }, { id: "conversations", text: "Thank you for every difficult conversation." }, { id: "staying", text: "Thank you for staying." }, { id: "space-4", text: "" },
      { id: "versions", text: "You have seen versions of me that many people never will." }, { id: "space-5", text: "" },
      { id: "somehow", text: "And somehow..." }, { id: "believing", text: "you never stopped believing in me." }, { id: "space-6", text: "" },
      { id: "relive", text: "If I could relive these fifteen months again..." }, { id: "space-7", text: "" },
      { id: "change", text: "I wouldn't change a thing." }, { id: "space-8", text: "" },
      { id: "because", text: "Because every conversation..." }, { id: "laugh", text: "every laugh..." }, { id: "disagreement", text: "every disagreement..." }, { id: "moment", text: "every moment..." }, { id: "space-9", text: "" },
      { id: "here", text: "led me here." },
    ],
  },
  throughMyEyes: {
    chapter: "Chapter IX",
    title: "If You Could See Yourself Through My Eyes",
    truths: [
      { id: "care", title: "You care deeply.", body: "Sometimes more than people ever realize." },
      { id: "celebrate", title: "You celebrate others.", body: "Even when you're quietly fighting your own battles." },
      { id: "ordinary", title: "You think you're ordinary.", body: "But ordinary people don't leave this kind of impact on someone's life." },
      { id: "flaws", title: "You overthink your flaws.", body: "Yet you rarely notice how much comfort you bring to others." },
      { id: "inspire", title: "You inspire quietly.", body: "Not through speeches, but through the way you keep showing up and becoming a better version of yourself." },
      { id: "kindness", title: "Your kindness isn't loud.", body: "That's exactly what makes it beautiful." },
      { id: "unforgettable", title: "You don't try to be unforgettable.", body: "Yet somehow... you are." },
    ],
    closing: ["I just hope... one day,", "you see yourself the way the people who love you already do."],
    next: { label: "Continue to Becoming", target: "chapter-10" },
  },
  becoming: {
    chapter: "Chapter X",
    title: "Becoming",
    intro: ["The beautiful thing isn't who you are today.", "It's how intentionally you're becoming who you dream of being."],
    milestones: [
      { id: "voice", emoji: "🎤", title: "You chose your voice.", description: "Singing wasn't just about music. It was about having the courage to let the world hear a part of you." },
      { id: "creating", emoji: "🎥", title: "You started creating.", description: "Creating content meant believing that your thoughts, your creativity, and your perspective deserved to exist beyond your own mind." },
      { id: "discipline", emoji: "🌱", title: "You chose discipline.", description: "Your niyamas weren't about perfection. They were quiet promises you made to yourself, and I admired how sincerely you tried to honor them." },
      { id: "growth", emoji: "✨", title: "You kept becoming.", description: "The most inspiring thing about you isn't where you've reached. It's that you never stop growing." },
    ],
    promise: "Promise me one thing.",
    closing: ["Years from now,", "when you finally become", "the person you're working so hard to be..."],
    finalLine: "Don't forget how far you've already come.",
    next: { label: "Continue to the Bouquet", target: "gallery" },
  },
  gallery: {
    chapter: "Chapter XI",
    title: "A Bouquet",
    intro: ["Every flower reminded me of you.", "So I made the flowers...", "You."],
    clickHint: "Click a flower",
    giftLabel: "FOR YOU",
    ribbon: "A LITTLE PIECE OF MY HEART",
    memoryLabel: "One of my favourite memories",
    videoBadge: "VIDEO",
    photos: [
      { id: 1, src: "/photos/1.jpeg", alt: "Memory one", caption: "You smiled... and somehow the whole picture smiled with you." },
      { id: 2, src: "/photos/2.jpeg", alt: "Memory two", caption: "Some people pose for pictures. You simply exist beautifully in them." },
      { id: 3, src: "/photos/3.jpeg", alt: "Memory three", caption: "I still don't know how you make ordinary moments look unforgettable." },
      { id: 4, src: "/photos/4.jpeg", alt: "Memory four", caption: "If happiness had a face, I think it would look something like this." },
      { id: 5, src: "/photos/5.jpeg", alt: "Memory five", caption: "This is one of those smiles I hope life never takes away from you." },
      { id: 6, src: "/photos/6.jpeg", alt: "Memory six", caption: "Every version of you has been beautiful, but watching you become yourself has been my favourite." },
      { id: 7, src: "/photos/7.jpeg", alt: "Memory seven", caption: "Some memories don't need dates. They simply stay." },
    ],
  },
  poem: {
    chapter: "Chapter XII",
    title: "The Way I See You",
    transition: ["A picture can remember a moment.", "A poem can remember a soul."],
    stanzas: [
      ["You are as beautiful as a scenery", "I would gladly travel miles to see,", "Not because a picture could hold you,", "But because some beauty", "is meant to be experienced quietly."],
      ["Your smile is like a field of sunflowers,", "turning even ordinary days", "toward something warmer,", "as though happiness itself", "had learned your name."],
      ["You laugh loudly,", "make the strangest expressions,", "break rules,", "get caught in lies you were never good at telling,", "and somehow make all your chaos", "feel like one of life's gentlest gifts."],
      ["You carry joy into every room,", "sometimes through your singing,", "sometimes through your childish mimicry,", "and sometimes simply by being present", "when the world feels too serious."],
      ["People see the cheerful girl,", "the fearless one,", "the one who keeps laughing."],
      ["But I have also seen", "the quiet battles behind that smile,", "the questions you do not always share,", "and the courage with which", "you continue anyway."],
      ["You dream with an open sky inside you.", "You chose your voice.", "You chose to create.", "You chose discipline.", "And every time you choose yourself,", "you give me another reason", "to feel proud of you."],
      ["You never tried to control my road.", "You listened,", "questioned,", "encouraged,", "and stayed—", "like a compass that never chose my destination,", "but reminded me where north was", "whenever I felt lost."],
      ["There were difficult days", "made lighter by one call from you,", "moments when your messages", "felt like rain after a storm,", "and silences that still carried", "the comfort of knowing", "you had not gone anywhere."],
      ["We have laughed at one another,", "misunderstood one another,", "hurt one another,", "and still,", "every time the bond was tested,", "we chose to repair", "what mattered more than our pride."],
      ["Fifteen months ago,", "you were someone", "I had only just begun to know."],
      ["Today,", "you are the keeper of stories", "I tell almost no one,", "the person whose smallest victories", "I celebrate,", "and one of the rare people", "whose presence makes life feel lighter."],
      ["If friendship could be drawn,", "ours would look like a folded map—", "covered in roads we have not travelled yet,", "plans we have not completed,", "and a future still waiting", "to become memory."],
      ["And if anyone asked me", "what you mean to me,", "I would not search for a perfect label."],
      ["Some bonds are too honest", "to be limited by a name."],
      ["I would simply say:"],
      ["You are one of the most beautiful chapters", "life wrote for me", "when I was not even looking for a story."],
      ["Happy Birthday."],
      ["May you keep laughing loudly,", "singing fearlessly,", "dreaming endlessly,", "and becoming exactly", "who you were always meant to be."],
      ["And through every new chapter,", "I hope life never lets you forget", "how deeply you are valued,", "how sincerely you are admired,", "and how proudly", "I will always root for you."],
    ],
  },
  video: {
    id: 8,
    eyebrow: "A message for you",
    title: "Some things are better said\nin my own voice.",
    playLabel: "Play message",
    fallbackText: "Your browser does not support video playback.",
    closingMessage: "I could write a thousand more lines,\nbut some things deserve to be heard.",
    src: "/videos/your-memory.mp4",
    alt: "A video message",
    badge: "VIDEO",
    caption: "Our story, in motion.",
    placeholder: false,
    placeholderTitle: "Your film goes here",
    placeholderInstructions: "Add your clip at public/video/message.mp4, then remove placeholder: true.",
  },
  finale: {
    // Replace this with her actual name.
    name: "Her Name",
    chapter: "The Final Chapter",
    duration: "15 months.",
    memories: [
      { id: "conversations", text: "Countless conversations." },
      { id: "laughter", text: "Endless laughter." },
      { id: "fights", text: "A few fights." },
      { id: "memories", text: "A thousand little memories." },
    ],
    reflection: ["And somehow,", "one unexpected friendship", "became one of the most meaningful", "chapters of my life."],
    birthday: "Happy Birthday,",
    wishes: [
      { id: "opening", lines: ["On your birthday,", "I do not only wish you happiness."] },
      { id: "dreams", lines: ["I wish you the courage", "to keep choosing your dreams."] },
      { id: "voice", lines: ["I wish you the confidence", "to let the world hear your voice."] },
      { id: "discipline", lines: ["I wish you the discipline", "to keep every promise", "you make to yourself."] },
      { id: "strength", lines: ["I wish you the strength", "to survive the days", "when your smile feels difficult."] },
      { id: "value", lines: ["And I wish you never forget", "how deeply you are valued,", "how sincerely you are admired,", "and how proudly", "I will always root for you."] },
    ],
    thankYou: {
      intro: "Thank you",
      items: [
        { id: "call", lines: ["for every call that made life lighter."] },
        { id: "expression", lines: ["For every strange expression", "that made me laugh."] },
        { id: "victory", lines: ["For every small victory", "you allowed me to celebrate."] },
        { id: "disagreement", lines: ["For every disagreement", "we chose to work through."] },
      ],
      ending: "And most importantly...",
      staying: "Thank you for staying.",
    },
    futureWish: ["Here’s to the person you are,", "the person you are becoming,", "and every memory", "we have not made yet."],
    divider: "∞",
    finalBirthdaySuffix: ".",
    thanks: "Thank you for existing.",
    chapterTwo: "See you in Chapter Two.",
  },
} as const;

export type StoryContent = typeof story;
export type GalleryPhoto = (typeof story.gallery.photos)[number];
